/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ArtistContent {
  'bio' : string,
  'poetryWorks' : Array<PoetryContent>,
  'biography' : string,
  'textWorks' : Array<PoetryContent>,
  'audioWorks' : Array<PoetryContent>,
  'videoWorks' : Array<PoetryContent>,
  'location' : StateOrUT,
  'artWorks' : Array<PoetryContent>,
  'images' : Array<ExternalBlob>,
}
export type ContentCategory = { 'imageShayaris' : null } |
  { 'kahanis' : null } |
  { 'kavitas' : null } |
  { 'ghazals' : null } |
  { 'shers' : null } |
  { 'nazms' : null } |
  { 'top5Shayaris' : null } |
  { 'audioFiles' : null } |
  { 'videos' : null };
export type ExternalBlob = Uint8Array;
export interface Image { 'url' : string, 'description' : [] | [string] }
export interface LayoutPreference {
  'style' : string,
  'featuredSection' : string,
  'colorScheme' : string,
}
export interface Poet {
  'id' : string,
  'content' : ArtistContent,
  'stateOrUT' : StateOrUT,
  'name' : string,
  'biography' : string,
  'notableWorks' : Array<string>,
  'website' : [] | [string],
  'socialMediaLinks' : Array<SocialMediaLink>,
  'awards' : Array<string>,
  'genres' : Array<string>,
  'layoutPreference' : LayoutPreference,
  'image' : [] | [Image],
  'avatarImage' : [] | [Image],
}
export interface PoetryContent {
  'id' : string,
  'title' : string,
  'content' : string,
  'audio' : [] | [ExternalBlob],
  'textVersion' : [] | [string],
  'visualAssets' : Array<ExternalBlob>,
  'category' : ContentCategory,
  'videos' : Array<ExternalBlob>,
  'images' : Array<ExternalBlob>,
}
export interface SocialMediaLink { 'url' : string, 'platform' : string }
export type State = { 'goa' : null } |
  { 'chhattisgarh' : null } |
  { 'telangana' : null } |
  { 'manipur' : null } |
  { 'rajasthan' : null } |
  { 'madhyaPradesh' : null } |
  { 'assam' : null } |
  { 'tripura' : null } |
  { 'mizoram' : null } |
  { 'kerala' : null } |
  { 'odisha' : null } |
  { 'tamilNadu' : null } |
  { 'arunachalPradesh' : null } |
  { 'andhraPradesh' : null } |
  { 'punjab' : null } |
  { 'uttarakhand' : null } |
  { 'karnataka' : null } |
  { 'haryana' : null } |
  { 'nagaland' : null } |
  { 'uttarPradesh' : null } |
  { 'himachalPradesh' : null } |
  { 'bihar' : null } |
  { 'sikkim' : null } |
  { 'jharkhand' : null } |
  { 'gujarat' : null } |
  { 'meghalaya' : null } |
  { 'maharashtra' : null } |
  { 'westBengal' : null };
export type StateOrUT = { 'unionTerritory' : UnionTerritory } |
  { 'state' : State };
export type UnionTerritory = { 'ladakh' : null } |
  { 'jammuAndKashmir' : null } |
  { 'chandigarh' : null } |
  { 'puducherry' : null } |
  { 'lakshadweep' : null } |
  { 'dadraAndNagarHaveliAndDamanAndDiu' : null } |
  { 'andamanAndNicobarIslands' : null } |
  { 'delhi' : null };
export interface UserProfile {
  'name' : string,
  'email' : [] | [string],
  'preferences' : { 'theme' : string, 'language' : string },
  'favoritePoets' : Array<string>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPoemToMainPoet' : ActorMethod<[PoetryContent], undefined>,
  'addPoemToPoet' : ActorMethod<[string, PoetryContent], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPoet' : ActorMethod<[string, Poet], undefined>,
  'deletePoet' : ActorMethod<[string], undefined>,
  'getAllPoets' : ActorMethod<[], Array<Poet>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMainPoet' : ActorMethod<[], Poet>,
  'getPoemsByCategory' : ActorMethod<
    [string, ContentCategory],
    Array<PoetryContent>
  >,
  'getPoet' : ActorMethod<[string], Poet>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateMainPoet' : ActorMethod<[Poet], undefined>,
  'updatePoet' : ActorMethod<[string, Poet], undefined>,
  'uploadFile' : ActorMethod<[ExternalBlob], ExternalBlob>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];