/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ContentCategory = IDL.Variant({
  'imageShayaris' : IDL.Null,
  'kahanis' : IDL.Null,
  'kavitas' : IDL.Null,
  'ghazals' : IDL.Null,
  'shers' : IDL.Null,
  'nazms' : IDL.Null,
  'top5Shayaris' : IDL.Null,
  'audioFiles' : IDL.Null,
  'videos' : IDL.Null,
});
export const PoetryContent = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'audio' : IDL.Opt(ExternalBlob),
  'textVersion' : IDL.Opt(IDL.Text),
  'visualAssets' : IDL.Vec(ExternalBlob),
  'category' : ContentCategory,
  'videos' : IDL.Vec(ExternalBlob),
  'images' : IDL.Vec(ExternalBlob),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UnionTerritory = IDL.Variant({
  'ladakh' : IDL.Null,
  'jammuAndKashmir' : IDL.Null,
  'chandigarh' : IDL.Null,
  'puducherry' : IDL.Null,
  'lakshadweep' : IDL.Null,
  'dadraAndNagarHaveliAndDamanAndDiu' : IDL.Null,
  'andamanAndNicobarIslands' : IDL.Null,
  'delhi' : IDL.Null,
});
export const State = IDL.Variant({
  'goa' : IDL.Null,
  'chhattisgarh' : IDL.Null,
  'telangana' : IDL.Null,
  'manipur' : IDL.Null,
  'rajasthan' : IDL.Null,
  'madhyaPradesh' : IDL.Null,
  'assam' : IDL.Null,
  'tripura' : IDL.Null,
  'mizoram' : IDL.Null,
  'kerala' : IDL.Null,
  'odisha' : IDL.Null,
  'tamilNadu' : IDL.Null,
  'arunachalPradesh' : IDL.Null,
  'andhraPradesh' : IDL.Null,
  'punjab' : IDL.Null,
  'uttarakhand' : IDL.Null,
  'karnataka' : IDL.Null,
  'haryana' : IDL.Null,
  'nagaland' : IDL.Null,
  'uttarPradesh' : IDL.Null,
  'himachalPradesh' : IDL.Null,
  'bihar' : IDL.Null,
  'sikkim' : IDL.Null,
  'jharkhand' : IDL.Null,
  'gujarat' : IDL.Null,
  'meghalaya' : IDL.Null,
  'maharashtra' : IDL.Null,
  'westBengal' : IDL.Null,
});
export const StateOrUT = IDL.Variant({
  'unionTerritory' : UnionTerritory,
  'state' : State,
});
export const ArtistContent = IDL.Record({
  'bio' : IDL.Text,
  'poetryWorks' : IDL.Vec(PoetryContent),
  'biography' : IDL.Text,
  'textWorks' : IDL.Vec(PoetryContent),
  'audioWorks' : IDL.Vec(PoetryContent),
  'videoWorks' : IDL.Vec(PoetryContent),
  'location' : StateOrUT,
  'artWorks' : IDL.Vec(PoetryContent),
  'images' : IDL.Vec(ExternalBlob),
});
export const SocialMediaLink = IDL.Record({
  'url' : IDL.Text,
  'platform' : IDL.Text,
});
export const LayoutPreference = IDL.Record({
  'style' : IDL.Text,
  'featuredSection' : IDL.Text,
  'colorScheme' : IDL.Text,
});
export const Image = IDL.Record({
  'url' : IDL.Text,
  'description' : IDL.Opt(IDL.Text),
});
export const Poet = IDL.Record({
  'id' : IDL.Text,
  'content' : ArtistContent,
  'stateOrUT' : StateOrUT,
  'name' : IDL.Text,
  'biography' : IDL.Text,
  'notableWorks' : IDL.Vec(IDL.Text),
  'website' : IDL.Opt(IDL.Text),
  'socialMediaLinks' : IDL.Vec(SocialMediaLink),
  'awards' : IDL.Vec(IDL.Text),
  'genres' : IDL.Vec(IDL.Text),
  'layoutPreference' : LayoutPreference,
  'image' : IDL.Opt(Image),
  'avatarImage' : IDL.Opt(Image),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'preferences' : IDL.Record({ 'theme' : IDL.Text, 'language' : IDL.Text }),
  'favoritePoets' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPoemToMainPoet' : IDL.Func([PoetryContent], [], []),
  'addPoemToPoet' : IDL.Func([IDL.Text, PoetryContent], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPoet' : IDL.Func([IDL.Text, Poet], [], []),
  'deletePoet' : IDL.Func([IDL.Text], [], []),
  'getAllPoets' : IDL.Func([], [IDL.Vec(Poet)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMainPoet' : IDL.Func([], [Poet], ['query']),
  'getPoemsByCategory' : IDL.Func(
      [IDL.Text, ContentCategory],
      [IDL.Vec(PoetryContent)],
      ['query'],
    ),
  'getPoet' : IDL.Func([IDL.Text], [Poet], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateMainPoet' : IDL.Func([Poet], [], []),
  'updatePoet' : IDL.Func([IDL.Text, Poet], [], []),
  'uploadFile' : IDL.Func([ExternalBlob], [ExternalBlob], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ContentCategory = IDL.Variant({
    'imageShayaris' : IDL.Null,
    'kahanis' : IDL.Null,
    'kavitas' : IDL.Null,
    'ghazals' : IDL.Null,
    'shers' : IDL.Null,
    'nazms' : IDL.Null,
    'top5Shayaris' : IDL.Null,
    'audioFiles' : IDL.Null,
    'videos' : IDL.Null,
  });
  const PoetryContent = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'audio' : IDL.Opt(ExternalBlob),
    'textVersion' : IDL.Opt(IDL.Text),
    'visualAssets' : IDL.Vec(ExternalBlob),
    'category' : ContentCategory,
    'videos' : IDL.Vec(ExternalBlob),
    'images' : IDL.Vec(ExternalBlob),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UnionTerritory = IDL.Variant({
    'ladakh' : IDL.Null,
    'jammuAndKashmir' : IDL.Null,
    'chandigarh' : IDL.Null,
    'puducherry' : IDL.Null,
    'lakshadweep' : IDL.Null,
    'dadraAndNagarHaveliAndDamanAndDiu' : IDL.Null,
    'andamanAndNicobarIslands' : IDL.Null,
    'delhi' : IDL.Null,
  });
  const State = IDL.Variant({
    'goa' : IDL.Null,
    'chhattisgarh' : IDL.Null,
    'telangana' : IDL.Null,
    'manipur' : IDL.Null,
    'rajasthan' : IDL.Null,
    'madhyaPradesh' : IDL.Null,
    'assam' : IDL.Null,
    'tripura' : IDL.Null,
    'mizoram' : IDL.Null,
    'kerala' : IDL.Null,
    'odisha' : IDL.Null,
    'tamilNadu' : IDL.Null,
    'arunachalPradesh' : IDL.Null,
    'andhraPradesh' : IDL.Null,
    'punjab' : IDL.Null,
    'uttarakhand' : IDL.Null,
    'karnataka' : IDL.Null,
    'haryana' : IDL.Null,
    'nagaland' : IDL.Null,
    'uttarPradesh' : IDL.Null,
    'himachalPradesh' : IDL.Null,
    'bihar' : IDL.Null,
    'sikkim' : IDL.Null,
    'jharkhand' : IDL.Null,
    'gujarat' : IDL.Null,
    'meghalaya' : IDL.Null,
    'maharashtra' : IDL.Null,
    'westBengal' : IDL.Null,
  });
  const StateOrUT = IDL.Variant({
    'unionTerritory' : UnionTerritory,
    'state' : State,
  });
  const ArtistContent = IDL.Record({
    'bio' : IDL.Text,
    'poetryWorks' : IDL.Vec(PoetryContent),
    'biography' : IDL.Text,
    'textWorks' : IDL.Vec(PoetryContent),
    'audioWorks' : IDL.Vec(PoetryContent),
    'videoWorks' : IDL.Vec(PoetryContent),
    'location' : StateOrUT,
    'artWorks' : IDL.Vec(PoetryContent),
    'images' : IDL.Vec(ExternalBlob),
  });
  const SocialMediaLink = IDL.Record({
    'url' : IDL.Text,
    'platform' : IDL.Text,
  });
  const LayoutPreference = IDL.Record({
    'style' : IDL.Text,
    'featuredSection' : IDL.Text,
    'colorScheme' : IDL.Text,
  });
  const Image = IDL.Record({
    'url' : IDL.Text,
    'description' : IDL.Opt(IDL.Text),
  });
  const Poet = IDL.Record({
    'id' : IDL.Text,
    'content' : ArtistContent,
    'stateOrUT' : StateOrUT,
    'name' : IDL.Text,
    'biography' : IDL.Text,
    'notableWorks' : IDL.Vec(IDL.Text),
    'website' : IDL.Opt(IDL.Text),
    'socialMediaLinks' : IDL.Vec(SocialMediaLink),
    'awards' : IDL.Vec(IDL.Text),
    'genres' : IDL.Vec(IDL.Text),
    'layoutPreference' : LayoutPreference,
    'image' : IDL.Opt(Image),
    'avatarImage' : IDL.Opt(Image),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'preferences' : IDL.Record({ 'theme' : IDL.Text, 'language' : IDL.Text }),
    'favoritePoets' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPoemToMainPoet' : IDL.Func([PoetryContent], [], []),
    'addPoemToPoet' : IDL.Func([IDL.Text, PoetryContent], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPoet' : IDL.Func([IDL.Text, Poet], [], []),
    'deletePoet' : IDL.Func([IDL.Text], [], []),
    'getAllPoets' : IDL.Func([], [IDL.Vec(Poet)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMainPoet' : IDL.Func([], [Poet], ['query']),
    'getPoemsByCategory' : IDL.Func(
        [IDL.Text, ContentCategory],
        [IDL.Vec(PoetryContent)],
        ['query'],
      ),
    'getPoet' : IDL.Func([IDL.Text], [Poet], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateMainPoet' : IDL.Func([Poet], [], []),
    'updatePoet' : IDL.Func([IDL.Text, Poet], [], []),
    'uploadFile' : IDL.Func([ExternalBlob], [ExternalBlob], []),
  });
};

export const init = ({ IDL }) => { return []; };