/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface PoetryContent {
    id: string;
    title: string;
    content: string;
    audio?: ExternalBlob;
    textVersion?: string;
    visualAssets: Array<ExternalBlob>;
    category: ContentCategory;
    videos: Array<ExternalBlob>;
    images: Array<ExternalBlob>;
}
export interface SocialMediaLink {
    url: string;
    platform: string;
}
export interface LayoutPreference {
    style: string;
    featuredSection: string;
    colorScheme: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Poet {
    id: string;
    content: ArtistContent;
    stateOrUT: StateOrUT;
    name: string;
    biography: string;
    notableWorks: Array<string>;
    website?: string;
    socialMediaLinks: Array<SocialMediaLink>;
    awards: Array<string>;
    genres: Array<string>;
    layoutPreference: LayoutPreference;
    image?: Image;
    avatarImage?: Image;
}
export interface ArtistContent {
    bio: string;
    poetryWorks: Array<PoetryContent>;
    biography: string;
    textWorks: Array<PoetryContent>;
    audioWorks: Array<PoetryContent>;
    videoWorks: Array<PoetryContent>;
    location: StateOrUT;
    artWorks: Array<PoetryContent>;
    images: Array<ExternalBlob>;
}
export interface Image {
    url: string;
    description?: string;
}
export type StateOrUT = {
    __kind__: "unionTerritory";
    unionTerritory: UnionTerritory;
} | {
    __kind__: "state";
    state: State;
};
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    name: string;
    email?: string;
    preferences: {
        theme: string;
        language: string;
    };
    favoritePoets: Array<string>;
}
export enum ContentCategory {
    imageShayaris = "imageShayaris",
    kahanis = "kahanis",
    kavitas = "kavitas",
    ghazals = "ghazals",
    shers = "shers",
    nazms = "nazms",
    top5Shayaris = "top5Shayaris",
    audioFiles = "audioFiles",
    videos = "videos"
}
export enum State {
    goa = "goa",
    chhattisgarh = "chhattisgarh",
    telangana = "telangana",
    manipur = "manipur",
    rajasthan = "rajasthan",
    madhyaPradesh = "madhyaPradesh",
    assam = "assam",
    tripura = "tripura",
    mizoram = "mizoram",
    kerala = "kerala",
    odisha = "odisha",
    tamilNadu = "tamilNadu",
    arunachalPradesh = "arunachalPradesh",
    andhraPradesh = "andhraPradesh",
    punjab = "punjab",
    uttarakhand = "uttarakhand",
    karnataka = "karnataka",
    haryana = "haryana",
    nagaland = "nagaland",
    uttarPradesh = "uttarPradesh",
    himachalPradesh = "himachalPradesh",
    bihar = "bihar",
    sikkim = "sikkim",
    jharkhand = "jharkhand",
    gujarat = "gujarat",
    meghalaya = "meghalaya",
    maharashtra = "maharashtra",
    westBengal = "westBengal"
}
export enum UnionTerritory {
    ladakh = "ladakh",
    jammuAndKashmir = "jammuAndKashmir",
    chandigarh = "chandigarh",
    puducherry = "puducherry",
    lakshadweep = "lakshadweep",
    dadraAndNagarHaveliAndDamanAndDiu = "dadraAndNagarHaveliAndDamanAndDiu",
    andamanAndNicobarIslands = "andamanAndNicobarIslands",
    delhi = "delhi"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addPoemToMainPoet(poem: PoetryContent): Promise<void>;
    addPoemToPoet(poetId: string, poem: PoetryContent): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createPoet(id: string, poet: Poet): Promise<void>;
    deletePoet(id: string): Promise<void>;
    getAllPoets(): Promise<Array<Poet>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMainPoet(): Promise<Poet>;
    getPoemsByCategory(poetId: string, category: ContentCategory): Promise<Array<PoetryContent>>;
    getPoet(id: string): Promise<Poet>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateMainPoet(updatedPoet: Poet): Promise<void>;
    updatePoet(id: string, updatedPoet: Poet): Promise<void>;
    uploadFile(file: ExternalBlob): Promise<ExternalBlob>;
}
import type { ArtistContent as _ArtistContent, ContentCategory as _ContentCategory, ExternalBlob as _ExternalBlob, Image as _Image, LayoutPreference as _LayoutPreference, Poet as _Poet, PoetryContent as _PoetryContent, SocialMediaLink as _SocialMediaLink, State as _State, StateOrUT as _StateOrUT, UnionTerritory as _UnionTerritory, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addPoemToMainPoet(arg0: PoetryContent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPoemToMainPoet(await to_candid_PoetryContent_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPoemToMainPoet(await to_candid_PoetryContent_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addPoemToPoet(arg0: string, arg1: PoetryContent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPoemToPoet(arg0, await to_candid_PoetryContent_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPoemToPoet(arg0, await to_candid_PoetryContent_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createPoet(arg0: string, arg1: Poet): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPoet(arg0, await to_candid_Poet_n16(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPoet(arg0, await to_candid_Poet_n16(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deletePoet(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePoet(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePoet(arg0);
            return result;
        }
    }
    async getAllPoets(): Promise<Array<Poet>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPoets();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPoets();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMainPoet(): Promise<Poet> {
        if (this.processError) {
            try {
                const result = await this.actor.getMainPoet();
                return from_candid_Poet_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMainPoet();
            return from_candid_Poet_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPoemsByCategory(arg0: string, arg1: ContentCategory): Promise<Array<PoetryContent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPoemsByCategory(arg0, to_candid_ContentCategory_n12(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPoemsByCategory(arg0, to_candid_ContentCategory_n12(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPoet(arg0: string): Promise<Poet> {
        if (this.processError) {
            try {
                const result = await this.actor.getPoet(arg0);
                return from_candid_Poet_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPoet(arg0);
            return from_candid_Poet_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n57(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n57(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateMainPoet(arg0: Poet): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMainPoet(await to_candid_Poet_n16(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMainPoet(await to_candid_Poet_n16(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updatePoet(arg0: string, arg1: Poet): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePoet(arg0, await to_candid_Poet_n16(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePoet(arg0, await to_candid_Poet_n16(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async uploadFile(arg0: ExternalBlob): Promise<ExternalBlob> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadFile(await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ExternalBlob_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadFile(await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ExternalBlob_n38(this._uploadFile, this._downloadFile, result);
        }
    }
}
async function from_candid_ArtistContent_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ArtistContent): Promise<ArtistContent> {
    return await from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_ContentCategory_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContentCategory): ContentCategory {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_Image_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Image): Image {
    return from_candid_record_n51(_uploadFile, _downloadFile, value);
}
async function from_candid_Poet_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Poet): Promise<Poet> {
    return await from_candid_record_n31(_uploadFile, _downloadFile, value);
}
async function from_candid_PoetryContent_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PoetryContent): Promise<PoetryContent> {
    return await from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_StateOrUT_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StateOrUT): StateOrUT {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid_State_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _State): State {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid_UnionTerritory_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UnionTerritory): UnionTerritory {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n54(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n56(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n38(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Image]): Image | null {
    return value.length === 0 ? null : from_candid_Image_n50(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n53(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    content: _ArtistContent;
    stateOrUT: _StateOrUT;
    name: string;
    biography: string;
    notableWorks: Array<string>;
    website: [] | [string];
    socialMediaLinks: Array<_SocialMediaLink>;
    awards: Array<string>;
    genres: Array<string>;
    layoutPreference: _LayoutPreference;
    image: [] | [_Image];
    avatarImage: [] | [_Image];
}): Promise<{
    id: string;
    content: ArtistContent;
    stateOrUT: StateOrUT;
    name: string;
    biography: string;
    notableWorks: Array<string>;
    website?: string;
    socialMediaLinks: Array<SocialMediaLink>;
    awards: Array<string>;
    genres: Array<string>;
    layoutPreference: LayoutPreference;
    image?: Image;
    avatarImage?: Image;
}> {
    return {
        id: value.id,
        content: await from_candid_ArtistContent_n32(_uploadFile, _downloadFile, value.content),
        stateOrUT: from_candid_StateOrUT_n43(_uploadFile, _downloadFile, value.stateOrUT),
        name: value.name,
        biography: value.biography,
        notableWorks: value.notableWorks,
        website: record_opt_to_undefined(from_candid_opt_n39(_uploadFile, _downloadFile, value.website)),
        socialMediaLinks: value.socialMediaLinks,
        awards: value.awards,
        genres: value.genres,
        layoutPreference: value.layoutPreference,
        image: record_opt_to_undefined(from_candid_opt_n49(_uploadFile, _downloadFile, value.image)),
        avatarImage: record_opt_to_undefined(from_candid_opt_n49(_uploadFile, _downloadFile, value.avatarImage))
    };
}
async function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    poetryWorks: Array<_PoetryContent>;
    biography: string;
    textWorks: Array<_PoetryContent>;
    audioWorks: Array<_PoetryContent>;
    videoWorks: Array<_PoetryContent>;
    location: _StateOrUT;
    artWorks: Array<_PoetryContent>;
    images: Array<_ExternalBlob>;
}): Promise<{
    bio: string;
    poetryWorks: Array<PoetryContent>;
    biography: string;
    textWorks: Array<PoetryContent>;
    audioWorks: Array<PoetryContent>;
    videoWorks: Array<PoetryContent>;
    location: StateOrUT;
    artWorks: Array<PoetryContent>;
    images: Array<ExternalBlob>;
}> {
    return {
        bio: value.bio,
        poetryWorks: await from_candid_vec_n34(_uploadFile, _downloadFile, value.poetryWorks),
        biography: value.biography,
        textWorks: await from_candid_vec_n34(_uploadFile, _downloadFile, value.textWorks),
        audioWorks: await from_candid_vec_n34(_uploadFile, _downloadFile, value.audioWorks),
        videoWorks: await from_candid_vec_n34(_uploadFile, _downloadFile, value.videoWorks),
        location: from_candid_StateOrUT_n43(_uploadFile, _downloadFile, value.location),
        artWorks: await from_candid_vec_n34(_uploadFile, _downloadFile, value.artWorks),
        images: await from_candid_vec_n40(_uploadFile, _downloadFile, value.images)
    };
}
async function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    content: string;
    audio: [] | [_ExternalBlob];
    textVersion: [] | [string];
    visualAssets: Array<_ExternalBlob>;
    category: _ContentCategory;
    videos: Array<_ExternalBlob>;
    images: Array<_ExternalBlob>;
}): Promise<{
    id: string;
    title: string;
    content: string;
    audio?: ExternalBlob;
    textVersion?: string;
    visualAssets: Array<ExternalBlob>;
    category: ContentCategory;
    videos: Array<ExternalBlob>;
    images: Array<ExternalBlob>;
}> {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        audio: record_opt_to_undefined(await from_candid_opt_n37(_uploadFile, _downloadFile, value.audio)),
        textVersion: record_opt_to_undefined(from_candid_opt_n39(_uploadFile, _downloadFile, value.textVersion)),
        visualAssets: await from_candid_vec_n40(_uploadFile, _downloadFile, value.visualAssets),
        category: from_candid_ContentCategory_n41(_uploadFile, _downloadFile, value.category),
        videos: await from_candid_vec_n40(_uploadFile, _downloadFile, value.videos),
        images: await from_candid_vec_n40(_uploadFile, _downloadFile, value.images)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    url: string;
    description: [] | [string];
}): {
    url: string;
    description?: string;
} {
    return {
        url: value.url,
        description: record_opt_to_undefined(from_candid_opt_n39(_uploadFile, _downloadFile, value.description))
    };
}
function from_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: [] | [string];
    preferences: {
        theme: string;
        language: string;
    };
    favoritePoets: Array<string>;
}): {
    name: string;
    email?: string;
    preferences: {
        theme: string;
        language: string;
    };
    favoritePoets: Array<string>;
} {
    return {
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n39(_uploadFile, _downloadFile, value.email)),
        preferences: value.preferences,
        favoritePoets: value.favoritePoets
    };
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    imageShayaris: null;
} | {
    kahanis: null;
} | {
    kavitas: null;
} | {
    ghazals: null;
} | {
    shers: null;
} | {
    nazms: null;
} | {
    top5Shayaris: null;
} | {
    audioFiles: null;
} | {
    videos: null;
}): ContentCategory {
    return "imageShayaris" in value ? ContentCategory.imageShayaris : "kahanis" in value ? ContentCategory.kahanis : "kavitas" in value ? ContentCategory.kavitas : "ghazals" in value ? ContentCategory.ghazals : "shers" in value ? ContentCategory.shers : "nazms" in value ? ContentCategory.nazms : "top5Shayaris" in value ? ContentCategory.top5Shayaris : "audioFiles" in value ? ContentCategory.audioFiles : "videos" in value ? ContentCategory.videos : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    unionTerritory: _UnionTerritory;
} | {
    state: _State;
}): {
    __kind__: "unionTerritory";
    unionTerritory: UnionTerritory;
} | {
    __kind__: "state";
    state: State;
} {
    return "unionTerritory" in value ? {
        __kind__: "unionTerritory",
        unionTerritory: from_candid_UnionTerritory_n45(_uploadFile, _downloadFile, value.unionTerritory)
    } : "state" in value ? {
        __kind__: "state",
        state: from_candid_State_n47(_uploadFile, _downloadFile, value.state)
    } : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ladakh: null;
} | {
    jammuAndKashmir: null;
} | {
    chandigarh: null;
} | {
    puducherry: null;
} | {
    lakshadweep: null;
} | {
    dadraAndNagarHaveliAndDamanAndDiu: null;
} | {
    andamanAndNicobarIslands: null;
} | {
    delhi: null;
}): UnionTerritory {
    return "ladakh" in value ? UnionTerritory.ladakh : "jammuAndKashmir" in value ? UnionTerritory.jammuAndKashmir : "chandigarh" in value ? UnionTerritory.chandigarh : "puducherry" in value ? UnionTerritory.puducherry : "lakshadweep" in value ? UnionTerritory.lakshadweep : "dadraAndNagarHaveliAndDamanAndDiu" in value ? UnionTerritory.dadraAndNagarHaveliAndDamanAndDiu : "andamanAndNicobarIslands" in value ? UnionTerritory.andamanAndNicobarIslands : "delhi" in value ? UnionTerritory.delhi : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    goa: null;
} | {
    chhattisgarh: null;
} | {
    telangana: null;
} | {
    manipur: null;
} | {
    rajasthan: null;
} | {
    madhyaPradesh: null;
} | {
    assam: null;
} | {
    tripura: null;
} | {
    mizoram: null;
} | {
    kerala: null;
} | {
    odisha: null;
} | {
    tamilNadu: null;
} | {
    arunachalPradesh: null;
} | {
    andhraPradesh: null;
} | {
    punjab: null;
} | {
    uttarakhand: null;
} | {
    karnataka: null;
} | {
    haryana: null;
} | {
    nagaland: null;
} | {
    uttarPradesh: null;
} | {
    himachalPradesh: null;
} | {
    bihar: null;
} | {
    sikkim: null;
} | {
    jharkhand: null;
} | {
    gujarat: null;
} | {
    meghalaya: null;
} | {
    maharashtra: null;
} | {
    westBengal: null;
}): State {
    return "goa" in value ? State.goa : "chhattisgarh" in value ? State.chhattisgarh : "telangana" in value ? State.telangana : "manipur" in value ? State.manipur : "rajasthan" in value ? State.rajasthan : "madhyaPradesh" in value ? State.madhyaPradesh : "assam" in value ? State.assam : "tripura" in value ? State.tripura : "mizoram" in value ? State.mizoram : "kerala" in value ? State.kerala : "odisha" in value ? State.odisha : "tamilNadu" in value ? State.tamilNadu : "arunachalPradesh" in value ? State.arunachalPradesh : "andhraPradesh" in value ? State.andhraPradesh : "punjab" in value ? State.punjab : "uttarakhand" in value ? State.uttarakhand : "karnataka" in value ? State.karnataka : "haryana" in value ? State.haryana : "nagaland" in value ? State.nagaland : "uttarPradesh" in value ? State.uttarPradesh : "himachalPradesh" in value ? State.himachalPradesh : "bihar" in value ? State.bihar : "sikkim" in value ? State.sikkim : "jharkhand" in value ? State.jharkhand : "gujarat" in value ? State.gujarat : "meghalaya" in value ? State.meghalaya : "maharashtra" in value ? State.maharashtra : "westBengal" in value ? State.westBengal : value;
}
function from_candid_variant_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Poet>): Promise<Array<Poet>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Poet_n30(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PoetryContent>): Promise<Array<PoetryContent>> {
    return await Promise.all(value.map(async (x)=>await from_candid_PoetryContent_n35(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n38(_uploadFile, _downloadFile, x)));
}
async function to_candid_ArtistContent_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ArtistContent): Promise<_ArtistContent> {
    return await to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_ContentCategory_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentCategory): _ContentCategory {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_Image_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Image): _Image {
    return to_candid_record_n28(_uploadFile, _downloadFile, value);
}
async function to_candid_Poet_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Poet): Promise<_Poet> {
    return await to_candid_record_n17(_uploadFile, _downloadFile, value);
}
async function to_candid_PoetryContent_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PoetryContent): Promise<_PoetryContent> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_StateOrUT_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StateOrUT): _StateOrUT {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_State_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: State): _State {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_UnionTerritory_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UnionTerritory): _UnionTerritory {
    return to_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n58(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    content: ArtistContent;
    stateOrUT: StateOrUT;
    name: string;
    biography: string;
    notableWorks: Array<string>;
    website?: string;
    socialMediaLinks: Array<SocialMediaLink>;
    awards: Array<string>;
    genres: Array<string>;
    layoutPreference: LayoutPreference;
    image?: Image;
    avatarImage?: Image;
}): Promise<{
    id: string;
    content: _ArtistContent;
    stateOrUT: _StateOrUT;
    name: string;
    biography: string;
    notableWorks: Array<string>;
    website: [] | [string];
    socialMediaLinks: Array<_SocialMediaLink>;
    awards: Array<string>;
    genres: Array<string>;
    layoutPreference: _LayoutPreference;
    image: [] | [_Image];
    avatarImage: [] | [_Image];
}> {
    return {
        id: value.id,
        content: await to_candid_ArtistContent_n18(_uploadFile, _downloadFile, value.content),
        stateOrUT: to_candid_StateOrUT_n21(_uploadFile, _downloadFile, value.stateOrUT),
        name: value.name,
        biography: value.biography,
        notableWorks: value.notableWorks,
        website: value.website ? candid_some(value.website) : candid_none(),
        socialMediaLinks: value.socialMediaLinks,
        awards: value.awards,
        genres: value.genres,
        layoutPreference: value.layoutPreference,
        image: value.image ? candid_some(to_candid_Image_n27(_uploadFile, _downloadFile, value.image)) : candid_none(),
        avatarImage: value.avatarImage ? candid_some(to_candid_Image_n27(_uploadFile, _downloadFile, value.avatarImage)) : candid_none()
    };
}
async function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    poetryWorks: Array<PoetryContent>;
    biography: string;
    textWorks: Array<PoetryContent>;
    audioWorks: Array<PoetryContent>;
    videoWorks: Array<PoetryContent>;
    location: StateOrUT;
    artWorks: Array<PoetryContent>;
    images: Array<ExternalBlob>;
}): Promise<{
    bio: string;
    poetryWorks: Array<_PoetryContent>;
    biography: string;
    textWorks: Array<_PoetryContent>;
    audioWorks: Array<_PoetryContent>;
    videoWorks: Array<_PoetryContent>;
    location: _StateOrUT;
    artWorks: Array<_PoetryContent>;
    images: Array<_ExternalBlob>;
}> {
    return {
        bio: value.bio,
        poetryWorks: await to_candid_vec_n20(_uploadFile, _downloadFile, value.poetryWorks),
        biography: value.biography,
        textWorks: await to_candid_vec_n20(_uploadFile, _downloadFile, value.textWorks),
        audioWorks: await to_candid_vec_n20(_uploadFile, _downloadFile, value.audioWorks),
        videoWorks: await to_candid_vec_n20(_uploadFile, _downloadFile, value.videoWorks),
        location: to_candid_StateOrUT_n21(_uploadFile, _downloadFile, value.location),
        artWorks: await to_candid_vec_n20(_uploadFile, _downloadFile, value.artWorks),
        images: await to_candid_vec_n11(_uploadFile, _downloadFile, value.images)
    };
}
function to_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    url: string;
    description?: string;
}): {
    url: string;
    description: [] | [string];
} {
    return {
        url: value.url,
        description: value.description ? candid_some(value.description) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email?: string;
    preferences: {
        theme: string;
        language: string;
    };
    favoritePoets: Array<string>;
}): {
    name: string;
    email: [] | [string];
    preferences: {
        theme: string;
        language: string;
    };
    favoritePoets: Array<string>;
} {
    return {
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none(),
        preferences: value.preferences,
        favoritePoets: value.favoritePoets
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    content: string;
    audio?: ExternalBlob;
    textVersion?: string;
    visualAssets: Array<ExternalBlob>;
    category: ContentCategory;
    videos: Array<ExternalBlob>;
    images: Array<ExternalBlob>;
}): Promise<{
    id: string;
    title: string;
    content: string;
    audio: [] | [_ExternalBlob];
    textVersion: [] | [string];
    visualAssets: Array<_ExternalBlob>;
    category: _ContentCategory;
    videos: Array<_ExternalBlob>;
    images: Array<_ExternalBlob>;
}> {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        audio: value.audio ? candid_some(await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.audio)) : candid_none(),
        textVersion: value.textVersion ? candid_some(value.textVersion) : candid_none(),
        visualAssets: await to_candid_vec_n11(_uploadFile, _downloadFile, value.visualAssets),
        category: to_candid_ContentCategory_n12(_uploadFile, _downloadFile, value.category),
        videos: await to_candid_vec_n11(_uploadFile, _downloadFile, value.videos),
        images: await to_candid_vec_n11(_uploadFile, _downloadFile, value.images)
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentCategory): {
    imageShayaris: null;
} | {
    kahanis: null;
} | {
    kavitas: null;
} | {
    ghazals: null;
} | {
    shers: null;
} | {
    nazms: null;
} | {
    top5Shayaris: null;
} | {
    audioFiles: null;
} | {
    videos: null;
} {
    return value == ContentCategory.imageShayaris ? {
        imageShayaris: null
    } : value == ContentCategory.kahanis ? {
        kahanis: null
    } : value == ContentCategory.kavitas ? {
        kavitas: null
    } : value == ContentCategory.ghazals ? {
        ghazals: null
    } : value == ContentCategory.shers ? {
        shers: null
    } : value == ContentCategory.nazms ? {
        nazms: null
    } : value == ContentCategory.top5Shayaris ? {
        top5Shayaris: null
    } : value == ContentCategory.audioFiles ? {
        audioFiles: null
    } : value == ContentCategory.videos ? {
        videos: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "unionTerritory";
    unionTerritory: UnionTerritory;
} | {
    __kind__: "state";
    state: State;
}): {
    unionTerritory: _UnionTerritory;
} | {
    state: _State;
} {
    return value.__kind__ === "unionTerritory" ? {
        unionTerritory: to_candid_UnionTerritory_n25(_uploadFile, _downloadFile, value.unionTerritory)
    } : value.__kind__ === "state" ? {
        state: to_candid_State_n23(_uploadFile, _downloadFile, value.state)
    } : value;
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: State): {
    goa: null;
} | {
    chhattisgarh: null;
} | {
    telangana: null;
} | {
    manipur: null;
} | {
    rajasthan: null;
} | {
    madhyaPradesh: null;
} | {
    assam: null;
} | {
    tripura: null;
} | {
    mizoram: null;
} | {
    kerala: null;
} | {
    odisha: null;
} | {
    tamilNadu: null;
} | {
    arunachalPradesh: null;
} | {
    andhraPradesh: null;
} | {
    punjab: null;
} | {
    uttarakhand: null;
} | {
    karnataka: null;
} | {
    haryana: null;
} | {
    nagaland: null;
} | {
    uttarPradesh: null;
} | {
    himachalPradesh: null;
} | {
    bihar: null;
} | {
    sikkim: null;
} | {
    jharkhand: null;
} | {
    gujarat: null;
} | {
    meghalaya: null;
} | {
    maharashtra: null;
} | {
    westBengal: null;
} {
    return value == State.goa ? {
        goa: null
    } : value == State.chhattisgarh ? {
        chhattisgarh: null
    } : value == State.telangana ? {
        telangana: null
    } : value == State.manipur ? {
        manipur: null
    } : value == State.rajasthan ? {
        rajasthan: null
    } : value == State.madhyaPradesh ? {
        madhyaPradesh: null
    } : value == State.assam ? {
        assam: null
    } : value == State.tripura ? {
        tripura: null
    } : value == State.mizoram ? {
        mizoram: null
    } : value == State.kerala ? {
        kerala: null
    } : value == State.odisha ? {
        odisha: null
    } : value == State.tamilNadu ? {
        tamilNadu: null
    } : value == State.arunachalPradesh ? {
        arunachalPradesh: null
    } : value == State.andhraPradesh ? {
        andhraPradesh: null
    } : value == State.punjab ? {
        punjab: null
    } : value == State.uttarakhand ? {
        uttarakhand: null
    } : value == State.karnataka ? {
        karnataka: null
    } : value == State.haryana ? {
        haryana: null
    } : value == State.nagaland ? {
        nagaland: null
    } : value == State.uttarPradesh ? {
        uttarPradesh: null
    } : value == State.himachalPradesh ? {
        himachalPradesh: null
    } : value == State.bihar ? {
        bihar: null
    } : value == State.sikkim ? {
        sikkim: null
    } : value == State.jharkhand ? {
        jharkhand: null
    } : value == State.gujarat ? {
        gujarat: null
    } : value == State.meghalaya ? {
        meghalaya: null
    } : value == State.maharashtra ? {
        maharashtra: null
    } : value == State.westBengal ? {
        westBengal: null
    } : value;
}
function to_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UnionTerritory): {
    ladakh: null;
} | {
    jammuAndKashmir: null;
} | {
    chandigarh: null;
} | {
    puducherry: null;
} | {
    lakshadweep: null;
} | {
    dadraAndNagarHaveliAndDamanAndDiu: null;
} | {
    andamanAndNicobarIslands: null;
} | {
    delhi: null;
} {
    return value == UnionTerritory.ladakh ? {
        ladakh: null
    } : value == UnionTerritory.jammuAndKashmir ? {
        jammuAndKashmir: null
    } : value == UnionTerritory.chandigarh ? {
        chandigarh: null
    } : value == UnionTerritory.puducherry ? {
        puducherry: null
    } : value == UnionTerritory.lakshadweep ? {
        lakshadweep: null
    } : value == UnionTerritory.dadraAndNagarHaveliAndDamanAndDiu ? {
        dadraAndNagarHaveliAndDamanAndDiu: null
    } : value == UnionTerritory.andamanAndNicobarIslands ? {
        andamanAndNicobarIslands: null
    } : value == UnionTerritory.delhi ? {
        delhi: null
    } : value;
}
async function to_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, x)));
}
async function to_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<PoetryContent>): Promise<Array<_PoetryContent>> {
    return await Promise.all(value.map(async (x)=>await to_candid_PoetryContent_n8(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
